---
services:
  adguard-cidre:
    build: .
    container_name: adguard-cidre
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris # change to your timezone
      - BLOCK_COUNTRIES=cn,ru # choose countries listed IP to block. Full lists here https://github.com/vulnebify/cidre/tree/main/output/cidr/ipv4
      - BLOCKLIST_CRON=0 6 * * * # at 6:00 every days
      - DOCKER_API_URL=http://socket-proxy-adguard:2375 # docker socket proxy
      - ADGUARD_CONTAINER_NAME=adguardhome # adguard container name
    volumes:
      - /path/to/adguard/confdir:/adguard

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy-adguard
    security_opt:
      - no-new-privileges:true
    environment:
      - CONTAINERS=1
      - ALLOW_RESTARTS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run